name: Build

on:
  workflow_dispatch:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: '-Dwarnings'

jobs:
  rustfmt:
    runs-on: ubuntu-latest
    name: 'Formatting'
    steps:
      - uses: actions/checkout@v4

      - name: Check formatting
        run: cargo fmt --check

  clippy:
    runs-on: ubuntu-latest
    name: 'Clippy'
    steps:
      - uses: actions/checkout@v4

      - uses: Swatinem/rust-cache@v2
        name: Cache dependencies

      - name: Clippy
        run: cargo clippy --all-targets --all-features

  build:
    name: 'Build & Test'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: Swatinem/rust-cache@v2
        name: Cache dependencies

      - name: Install build deps
        run: ./.github/scripts/ubuntu_setup.sh

      - name: Build
        run: cargo build --verbose
